# docker-compose run --service-ports rist_server
version: "3.9"
services:
  rist:
    image: wdion/rist:latest
    build: ./rist_bin
  rist_server:
    depends_on:
      - rist
    #image: gaiterjones/darwin-streaming:latest
    image: wdion/rist_server:1.0
    build: ./rist_service
    container_name: rist_server
    #user: "${UID}:${GID}"
    #user: 1000:102
    #user: 0:0
    ports:
      - "8201:8201/tcp"
      - "8201:8201/udp"
      - "8299:8299/tcp"
      - "8299:8299/udp"
    expose: 
      - 8201
      - 8299
    stdin_open: true # docker run -i
    tty: true # docker run -t
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: unless-stopped

